export const QUESTIONS = [
  {
    id: 1,
    question: "What is 1 + 1?",
    listQuestion: [
      { answer: "1", correct: false },
      { answer: "2", correct: true },
      { answer: "3", correct: false },
      { answer: "4", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 2,
    question: "What is 2 + 2?",
    listQuestion: [
      { answer: "2", correct: false },
      { answer: "3", correct: false },
      { answer: "4", correct: true },
      { answer: "5", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 3,
    question: "What is 3 + 3?",
    listQuestion: [
      { answer: "4", correct: false },
      { answer: "5", correct: false },
      { answer: "6", correct: true },
      { answer: "7", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 4,
    question: "What is 4 + 4?",
    listQuestion: [
      { answer: "6", correct: false },
      { answer: "7", correct: false },
      { answer: "8", correct: true },
      { answer: "9", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 5,
    question: "What is 5 + 5?",
    listQuestion: [
      { answer: "8", correct: false },
      { answer: "9", correct: false },
      { answer: "10", correct: true },
      { answer: "11", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 6,
    question: "What is 6 + 6?",
    listQuestion: [
      { answer: "10", correct: false },
      { answer: "11", correct: false },
      { answer: "12", correct: true },
      { answer: "13", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 7,
    question: "What is 7 + 7?",
    listQuestion: [
      { answer: "12", correct: false },
      { answer: "13", correct: false },
      { answer: "14", correct: true },
      { answer: "15", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 8,
    question: "What is 8 + 8?",
    listQuestion: [
      { answer: "14", correct: false },
      { answer: "15", correct: false },
      { answer: "16", correct: true },
      { answer: "17", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 9,
    question: "What is 9 + 9?",
    listQuestion: [
      { answer: "16", correct: false },
      { answer: "17", correct: false },
      { answer: "18", correct: true },
      { answer: "19", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 10,
    question: "What is 10 + 10?",
    listQuestion: [
      { answer: "18", correct: false },
      { answer: "19", correct: false },
      { answer: "20", correct: true },
      { answer: "21", correct: false },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 11,
    question: "What is 11 + 11?",
    listQuestion: [
      { answer: "19", correct: false },
      { answer: "20", correct: false },
      { answer: "21", correct: false },
      { answer: "22", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 12,
    question: "What is 12 + 12?",
    listQuestion: [
      { answer: "21", correct: false },
      { answer: "22", correct: false },
      { answer: "23", correct: false },
      { answer: "24", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 13,
    question: "What is 13 + 13?",
    listQuestion: [
      { answer: "23", correct: false },
      { answer: "24", correct: false },
      { answer: "25", correct: false },
      { answer: "26", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 14,
    question: "What is 14 + 14?",
    listQuestion: [
      { answer: "25", correct: false },
      { answer: "26", correct: false },
      { answer: "27", correct: false },
      { answer: "28", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 15,
    question: "What is 15 + 15?",
    listQuestion: [
      { answer: "27", correct: false },
      { answer: "28", correct: false },
      { answer: "29", correct: false },
      { answer: "30", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 16,
    question: "What is 16 + 16?",
    listQuestion: [
      { answer: "29", correct: false },
      { answer: "30", correct: false },
      { answer: "31", correct: false },
      { answer: "32", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 17,
    question: "What is 17 + 17?",
    listQuestion: [
      { answer: "31", correct: false },
      { answer: "32", correct: false },
      { answer: "33", correct: false },
      { answer: "34", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 18,
    question: "What is 18 + 18?",
    listQuestion: [
      { answer: "33", correct: false },
      { answer: "34", correct: false },
      { answer: "35", correct: false },
      { answer: "36", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 19,
    question: "What is 19 + 19?",
    listQuestion: [
      { answer: "35", correct: false },
      { answer: "36", correct: false },
      { answer: "37", correct: false },
      { answer: "38", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
  {
    id: 20,
    question: "What is 20 + 20?",
    listQuestion: [
      { answer: "37", correct: false },
      { answer: "38", correct: false },
      { answer: "39", correct: false },
      { answer: "40", correct: true },
    ],
    choseAnswer: -1,
    point: 0,
  },
];
